sqli_eztoolbox_entitymanager_homepage:
    path: /sqli-admin/entities/{tabname}
    controller: 'SQLI\EzToolboxBundle\Controller\EntitiesController::listAllEntitiesAction'
    defaults:
        tabname: 'default'

sqli_eztoolbox_entitymanager_entity_remove_element:
    path: /sqli-admin/entity/{fqcn}/remove/{compound_id}
    defaults: { _controller: 'SQLI\EzToolboxBundle\Controller\EntitiesController::removeElementAction' }

sqli_eztoolbox_entitymanager_entity_edit_element:
    path: /sqli-admin/entity/{fqcn}/edit/{compound_id}
    defaults: { _controller: 'SQLI\EzToolboxBundle\Controller\EntitiesController::editElementAction' }

sqli_eztoolbox_entitymanager_entity_create_element:
    path: /sqli-admin/entity/{fqcn}/create
    defaults: { _controller: 'SQLI\EzToolboxBundle\Controller\EntitiesController::createElementAction' }

sqli_eztoolbox_entitymanager_entity_export_csv:
    path: /sqli-admin/entity/{fqcn}/csv
    defaults: { _controller: 'SQLI\EzToolboxBundle\Controller\EntitiesController::exportCSVAction' }

sqli_eztoolbox_entitymanager_entity_homepage_reset_filter:
    path: /sqli-admin/entity/{fqcn}/reset
    controller: 'SQLI\EzToolboxBundle\Controller\EntitiesController::resetFilterAction'

# Content Type Installer
sqli_eztoolbox_contenttype_installer_list:
    path: /sqli-admin/contenttype_installer/list
    controller: 'SQLI\EzToolboxBundle\Controller\ContentTypeInstallerController::listAction'

sqli_eztoolbox_contenttype_installer_export:
    path: /sqli-admin/contenttype_installer/export
    controller: 'SQLI\EzToolboxBundle\Controller\ContentTypeInstallerController::exportAction'

# Keep this route at end
sqli_eztoolbox_entitymanager_entity_homepage:
    path: /sqli-admin/entity/{fqcn}/{sort_column}/{sort_order}
    controller: 'SQLI\EzToolboxBundle\Controller\EntitiesController::showEntityAction'
    defaults:
        sort_column: 'id'
        sort_order: 'ASC'