<?php

namespace SQLI\EzToolboxBundle\Repository\Doctrine;

/**
 * ParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
